# Site settings
title: Visualizing Capital
email: paulcavallaro@gmail.com
description: "A blog dedicated to summarizing and visualizing Thomas Piketty's Capital in the Twenty First Century"
baseurl: "/capital-piketty"
url: "http://paulcavallaro.github.io/capital-piketty"
twitter_username: chewedwire
github_username:  paulcavallaro

# Build settings
markdown: kramdown
permalink: pretty
